// <auto-generated />
namespace awsome_gymn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class attendance_module_added_controller_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(attendance_module_added_controller_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202309240423124_attendance_module_added_controller_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
