// <auto-generated />
namespace awsome_gymn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class enrollmentcreaed4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enrollmentcreaed4));
        
        string IMigrationMetadata.Id
        {
            get { return "202309171435221_enrollmentcreaed4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
