// <auto-generated />
namespace awsome_gymn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class role_added_initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(role_added_initial));
        
        string IMigrationMetadata.Id
        {
            get { return "202309101300259_role_added_initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
