// <auto-generated />
namespace awsome_gymn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class trainer_trainingsession_class_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trainer_trainingsession_class_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202309101322012_trainer_trainingsession_class_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
