// <auto-generated />
namespace awsome_gymn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class trainingsession_created2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trainingsession_created2));
        
        string IMigrationMetadata.Id
        {
            get { return "202309101557492_trainingsession_created2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
